### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by Israa91** [GSG-G9/Rawdaty#6]
relates #3 
### .travis.yml
```
language: node_js

node_js:
  - lts/* 

services:
  - postgresql

before_script:
  - psql -c "create database db_test_name" -U postgres
  - psql -c "create user username with password '12';" -U postgres
env: 
  global:
  - PGPORT=5432
test:
  adapter: postgresql
  database: db_test_name
```
